### ISSUE TITLE
Option to share the automatically generated birthday calendar without sharing the address book

### ISSUE THREAD

**Issue by UserXH726** [nextcloud/calendar#1307]
I'm not sure this is a missing feature or a bug...

I want to share the automatically generated birthday calendar without sharing the address book. But there is no option???

### Steps to reproduce
1. Create a birthday value in a contact in Contacts App
2. An automatically created birthday calendar will appear in the calendar app.
3. Try to share the calendar the known way you share normal calendars.

### Nextcloud
NC 15.0.5
Calendar 1.6.4
Contacts 3.0.5

**Comment by jangop** [comment]
> as far as i know the calendar is already shareable but it just misses a sharing button in the calendar.

If by “is already shareable” you mean that the automatically generated birthday calendar can already be accessed without authentication, could you explain how?

**Comment by georgehrke** [comment]
In theory it should be possible by sending a special CalDAV request ...
```
curl 'http://nextcloud.local/remote.php/dav/calendars/<username>/<calendaruri>' -H 'Depth: 0' --data-binary '<x4:publish-calendar xmlns:x4="http://calendarserver.org/ns/"/>' 
```

**Comment by jangop** [comment]
Don't authentication headers contradict the ”without authentication“ part?

**Comment by georgehrke** [comment]
You have to send that request to publish the calendar, afterwards you will be able to access it via it's publicURI

**Comment by georgehrke** [comment]
This will require changes in the server, because birthday calendars are not shareable by default at the moment. We are past feature freeze for 19, so this will have to wait for 20.

**Comment by georgehrke** [comment]
I added this to our overview ticket: https://github.com/nextcloud/server/issues/20096

**Comment by tdoerschel** [comment]
Hi,
I am not sure if this is related to here, so please tell me if I should open a new issue:
We use a shared address book (owned by a generic account).
Only the Birthday Calendar of the generic account shows the contact's birthdays.

-> the birthday calendar does not included contacts from shared address books.
That would be ok IF I could share the "generic account's" birthday calendar. But I cannot.

As far as I can see there is no way to display Birthdays from a shared address book.
I believe it was working in the past somehow, but I missed the point when or how it stopped working.
(Just happened that today is 2 out of 6 peoples birthday :-)

**Comment by bemyak** [comment]
I've tried sharing the `contact_birthdays` calendar as was suggested by @georgehrke, but it always gives me:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error 
  xmlns:d="DAV:" 
  xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>Access denied</s:message>
</d:error>
```

I don't get the same error with other calendars.

**Comment by soeffi** [comment]
> This will require changes in the server, because birthday calendars are not shareable by default at the moment. We are past feature freeze for 19, so this will have to wait for 20.

Does that imply that 


> In theory it should be possible by sending a special CalDAV request ...
> 
> ```
> curl 'http://nextcloud.local/remote.php/dav/calendars/<username>/<calendaruri>' -H 'Depth: 0' --data-binary '<x4:publish-calendar xmlns:x4="http://calendarserver.org/ns/"/>' 
> ```

 won't work?

**Comment by Tina-42** [comment]
Hey, I was also searching for this and this thread was one of the first I found. So I wanted an .ics link to integrate my birthday calendar into my GetHomepage calendar widget, but with no unauthenticated .ics link it doesn't work.
My solution was to modify a script I had already written to backup my calendars, and call it every 15 minutes via cron and have it write the birthday calendar into a directory that is readable by my caddy. Then in caddy I would share the calendar via an ics link. And since it is unauthenticated, I added a "salt" string to the url to make it unguessable - similar to how Google Calendar does it. So with that I now have my birthday calendar along with a public holiday calendar and my actual calendar integrated into a nice list of upcoming events in my GetHomepage screen :-)

So if you're interested in this workaround, here it is:

I created the "salt" for the url with
```
openssl rand -hex 64
```
which gives you a string like e.g. 
```
2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8
```

then my calendar back-up script modified to just download the birthday calendar:
(I left in the parts I commented out from it being a backup script if you decide to also want to repurpose it for that)
```
#!/usr/bin/env bash
set -Eeuo pipefail

# ---- config ----
BASE_URL="https://nc.nextcloud-url.de"
USER="tina"     # used in URL paths, not for auth
BACKUP_DIR="/opt/caddy2/www/calendar/2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8"
#RETENTION_DAYS=60                   # prune old backups

# List the DAV exports you want (calendars and address books)
# Calendars:
CAL_URLS=(
  #"$BASE_URL/remote.php/dav/calendars/$USER/personal?export"
  "$BASE_URL/remote.php/dav/calendars/$USER/contact_birthdays?export"
  #"$BASE_URL/remote.php/dav/calendars/$USER/work?export"
)
# Contacts (address books):
AB_URLS=(
  #"$BASE_URL/remote.php/dav/addressbooks/users/$USER/contacts?export"
  #"$BASE_URL/remote.php/dav/addressbooks/users/$USER/family?export"
)

#ts="$(date +%Y-%m-%d_%H-%M-%S)"
#outdir="$BACKUP_DIR/$ts"
outdir="$BACKUP_DIR"
#mkdir -p "$outdir"

curl_common=(
  --silent --show-error --fail --location
  --netrc         # read creds from ~/.netrc
)

log() { printf '[%s] %s\n' "$(date +%F\ %T)" "$*"; }

log "Starting Nextcloud DAV export → $outdir"

# Calendars
for u in "${CAL_URLS[@]}"; do
  name="$(printf '%s\n' "$u" | sed -E 's#.*/calendars/[^/]+/([^?]+).*#\1#')"
  log "Downloading calendar: $name"
  curl "${curl_common[@]}" "$u" -o "$outdir/calendar_${name}.ics"
done

# Address books
#for u in "${AB_URLS[@]}"; do
#  name="$(printf '%s\n' "$u" | sed -E 's#.*/addressbooks/users/[^/]+/([^?]+).*#\1#')"
#  log "Downloading addressbook: $name"
#  curl "${curl_common[@]}" "$u" -o "$outdir/contacts_${name}.vcf"
#done

# quick integrity sanity checks (non-empty)
#find "$outdir" -type f -size 0 -print -quit | grep -q . && {
#  echo "Error: got zero-byte export(s) in $outdir" >&2
#  exit 1
#}

# Retention
#find "$BACKUP_DIR" -maxdepth 1 -type d -name '20*' -mtime +"$RETENTION_DAYS" -print -exec rm -rf {} +

log "Done."
```

The scripts expects your login credentials in $HOME/.netrc like so:
```
# one entry per hostname (no scheme/port)
machine nc.nextcloud-url.de
  login tina
  password XXXXX-XXXXX-XXXXX-XXXXX-XXXXX
```
The password here is a NextCloud App Password as generated via NextCloud->Settings → Security → Create new app password but could be your regular password. Don't forget to "chmod 600" the .netrc file

So this script is then run by cronjob:
```
*/15 * * * * /opt/caddy2/nc-dav-backup.sh >>/opt/caddy2/nc-dav-backup.log 2>&1
```
and creates calendars named 
```
/opt/caddy2/www/calendar/2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8/calendar_contact_birthdays.ics
```
(so if you plan on doing this for multiple users, each one needs their own salt)

/opt/caddy2 is the base path of my intranet caddy instance, and via docker I shared /opt/caddy2/www into the container under the same name.

Then in the caddy Caddyfile this is how I set it up:
```
https://caddy2.intranet-url.de/ {
    handle_path /2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8/* {
        root * /opt/caddy2/www/calendar/2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8
        @ics path *.ics
        header @ics Content-Type "text/calendar; charset=utf-8"
        header {
            -Server
            Cache-Control "no-store"
        }
        file_server
    }
    respond "Go away!"
    tls internal
    log {
            output file /opt/caddy2/www/www_access.log {
                    roll_size 10MiB
                    roll_keep 7
                    roll_keep_for 48h
            }
            format console
            level DEBUG
    }

}
```

and so just for completeness, this is how my config block in GetHomepage services.yaml looks like for my main nextcloud calendar, plus birthday calendar, plus public holiday calendar:
```
 - Termine:
      icon: mdi-bat-#13bef9
      title: false
      widget:
        type: calendar
        view: agenda
        timezone: Europe/Berlin
        maxEvents: 10
        daysToShow: 6000
        showTime: true
        integrations:
          - type: ical
            url: https://nc.bat-tina.de/remote.php/dav/public-calendars/w8J78Ei2Qxr6oxHd?export
            name: Kalender
            color: cyan
            params:
              showName: false
          - type: ical
            url: https://caddy2.fritz.box/2a32ba307a96c0ddc37dda71e2987b77a2c502be41a3aac44c775dbe4901a8f059058d3720ae31e83816c7d98d31f52f7181c73465b227685a5b03fdd48804d8/calendar_contact_birthdays.ics
            name: Geburtstag
            color: yellow
            params:
              showName: true
          - type: ical
            url: https://onlinekalender.info/feiertage/deutschland/nordrhein-westfalen.ics
            name: Feiertag
            color: red
            params:
              showName: true
```
