### ISSUE TITLE
Remove scrollbars in Firefox

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar#1815]
Firefox adds horizontal and vertical scrollbars due to

```css
.fc * {
  box-sizing: content-box !important;
}
```

https://github.com/nextcloud/calendar/pull/1809#issuecomment-574569018

**Comment by georgehrke** [comment]
tl;dr:
- full-calendar is using a mix of `border-box` and `content-box`:
![3FD944A5-F77A-44BE-91A4-0CC45CABC7B6](https://user-images.githubusercontent.com/1250540/72423311-55a04900-3784-11ea-801b-838db3465423.png)
- the server is setting it to `border-box`:
```css
#content[class*='app-'] * {
    box-sizing: border-box;
}
```
That breaks plenty of things including positioning of events
- We override the server css for fullcalendar and set it to content box:
```
.fc * {
    box-sizing: content-box !important;
}
```
Which is causing the scrollbar issue in Firefox.
