### ISSUE TITLE
Simple editor shows up off screen in month view

### ISSUE THREAD

**Issue by dominic-p** [nextcloud/calendar#1934]
### Steps to reproduce
1. Switch to month view and create enough events in a day so that the +X more shows up
2. Click to show more events
3. Click one of the events to see more

### Expected behaviour
The simplified editor should show up next to the event

### Actual behaviour
The editor shows up half way off the screen

![calendar screenshot](https://user-images.githubusercontent.com/1195080/73385099-628f6300-4281-11ea-882d-f7e191da9511.png)

### Calendar app
**Calendar app version:** 2.0.1

**CalDAV-clients used:** NA

### Client configuration
**Browser:** Firefox 72.0.2

**Operating system:** Windows 10

### Server configuration

**Operating system**: Ubuntu

**Web server:** Nginx

**Database:** NA

**PHP version:** NA

**Nextcloud Version:** 17.0.2

By the way, I use this CSS to blur out calendar details for screenshots. I figured I would post it here in case it will help anyone else:

```css
body, textarea, .fc-title, #app-navigation#app-navigation .app-navigation-entry__title, .multiselect__single {
    color: transparent !important;
    text-shadow: 0 0 20px rgb(0,0,0);
}
.avatardiv {
    filter: blur(20px);
}
```
