### ISSUE TITLE
Datepicker navigation buttons not visible on dark mode on macOS in Firefox

### ISSUE THREAD

**Issue by frlan** [nextcloud/calendar#5164]
### Steps to reproduce

1. Switch to dark mode
2. Try to edit a date of an event

### Expected behavior

The arrows should be visible

### Actual behaviour

The arrows are not easily visible

### Calendar app version

4.3.3

### Browser

Firefox 

### Client operating system

macOS

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.6

### Updated from an older installed version or fresh install

None

### Additional info

<img width="415" alt="Bildschirmfoto 2023-04-26 um 08 33 53" src="https://user-images.githubusercontent.com/1010248/234490080-0947cc1c-8188-48da-bd63-2c12be81564e.png">

**Comment by ChristophWurst** [comment]
> Switch to dark mode

Is your OS set to dark mode?
Is your browser set to dark mode?
Is Nextcloud set to dark mode?

There are 8 possible combinations with these settings above. It's relevant for reproduction.

**Comment by frlan** [comment]
Nextcloud is set to system default

<img width="728" alt="Bildschirmfoto 2023-04-26 um 11 41 47" src="https://user-images.githubusercontent.com/1010248/234536953-4999101a-2fbd-4106-839e-0822271e3a97.png">

Browser is set to default. 

macOS is set to dark mode
﻿
<img width="569" alt="Bildschirmfoto 2023-04-26 um 11 43 11" src="https://user-images.githubusercontent.com/1010248/234537310-f4f6b4f8-52f7-49ab-8ac3-5e211c135bfb.png">

**Comment by nickian** [comment]
I noticed this as well. Here is a temporary fix. Install the custom CSS app. Add this to it.

```css
.mx-datepicker-main .mx-calendar-header .mx-btn-icon-double-left, .mx-datepicker-main .mx-calendar-header .mx-btn-icon-left, .mx-datepicker-main .mx-calendar-header .mx-btn-icon-right, .mx-datepicker-main .mx-calendar-header .mx-btn-icon-double-right {
    background-color: #fff;
}
```
